### PR TITLE
Merge in the latest changes from rubycentral/cfp-app

### PR DESCRIPTION
**Pull request by brandonjmckay**

### CODE REVIEW

**Comment by wifelette** [comment]
Waiting on @brandonjmckay's confirmation that he's run the tests, but this otherwise looks great! :+1:

**Comment by brandonjmckay** [comment]
Awesome. If I can, I'll try to run the tests before I leave work for the day. If not, maybe tomorrow.

**Comment by wifelette** [comment]
@brandonjmckay I'm pretty sure the version I'm testing on live already includes these changes. Just running off your local copy then?

Can you confirm that this ought be merged?

**Comment by brandonjmckay** [comment]
Yes, the Heroku version is essentially this branch. I created a PR so that we could go over it before I just merged it in.

Probably not that big a deal to just pull this in, and then create smaller PRs for any bugs that come up.

**Comment by wifelette** [comment]
Great. I've already gone through the live version looking for bugs and whatnot... as you can see from the copious issues ;) So we can work from there, hope you've still got time to help with some of em'!

**Pull request merged**
